# Generated by Django 5.0.6 on 2024-06-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Корзина продуктов', 'verbose_name_plural': 'Корзины продуктов'},
        ),
    ]
